# The meta-data of site.
# © 2017-2019 Cotes Chung
# MIT License

ga_id: 'your_google_analytics_id'

disqus_shortname: 'your_disqus_shortname'

first_run: 2017  # The year of the site's first run.

url: 'http://127.0.0.1:4000' # Replace with your domain
