# The meta-data of site.
# © 2017-2019 Cotes Chung
# MIT License

ga_id: 'your_google_analytics_id'

disqus-shortname: 'your_disqus_shortname'

publication-date: 2017  # The Site's first publication date.

url: 'http://localhost:4000' # Replace with your domain